
# Download this extension for use
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# test user token:
# NzlkYmViODE2NTgyLTE=

# LOGIN
# POST http://localhost:8080/auth/login
# content-type: application/json

# {
#     "email": "g741980@gmail.com",
#     "password": "12345678"
# }

# GET USERS
# GET http://localhost:8080/user
# Authorization: NzlkYmViODE2NTgyLTE=

# # GET PROJECTS
# GET http://localhost:8080/project
# Authorization: NzlkYmViODE2NTgyLTE=

# # PROJECTS CREATION
# POST  http://localhost:8080/project/
# Authorization: NzlkYmViODE2NTgyLTE=
# content-type: application/json

# {
#     "title": "test project",
#     "color":0
# }

# # GET TASKS
# GET http://localhost:8080/taskProject/2
# Authorization: NzlkYmViODE2NTgyLTE=

# # GET TASK
# GET http://localhost:8080/task/5
# Authorization: NzlkYmViODE2NTgyLTE=

# # TASK CREATION
# POST  http://localhost:8080/task/
# Authorization: NzlkYmViODE2NTgyLTE=
# content-type: application/json

# {
#     "title": "first task",
#     "description": "description",
#     "dueDate": "2022-05-29 15:50:07.413562417 +0000 UTC",
#     "projectId":2,
#     "statusId":0,
#     "userId":1,
#     "cost":0
# }

# TASK EDIT
PUT  http://localhost:8080/task/
Authorization: NzlkYmViODE2NTgyLTE=
content-type: application/json

{"title": "api docs", "description": "", "projectId": 2, "dueDate": "2022-12-03T13:33:27.256", "cost": 0, "statusId": 0, "assignerId": 3, "id": 5}

# DELETE TASKS
# DELETE http://localhost:8080/task/48
# Authorization: NzlkYmViODE2NTgyLTE=
