
# Download this extension for use
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# test user token:
# NzlkYmViODE2NTgyLTE=

# # # LOGIN
# POST http://localhost:8080/auth/login
# content-type: application/json

# {
#     "email": "g741980@gmail.com",
#     "password": "12345678"
# }

# # GET USERS
# GET http://localhost:8080/user/me
# Authorization: NzlkYmViODE2NTgyLTE=

# # GET USERS FROM PROJECT
# GET http://localhost:8080/projectMembers/2
# Authorization: NzlkYmViODE2NTgyLTE=

# # ADD USERS TO PROJECT
# PUT http://localhost:8080/projectMembers/24?email=a.negovskaya@yandex.ru
# Authorization: NzlkYmViODE2NTgyLTE=

# # DELETE USERS FROM PROJECT
# DELETE http://localhost:8080/projectMembers/25?userId=3
# Authorization: NzlkYmViODE2NTgyLTE=

# # GET PROJECTS
# GET http://localhost:8080/project
# Authorization: NzlkYmViODE2NTgyLTE=

# # GET PROJECTS BY ID
# GET http://localhost:8080/project/2
# Authorization: NzlkYmViODE2NTgyLTE=

# # PROJECTS CREATION
# POST  http://localhost:8080/project
# Authorization: NzlkYmViODE2NTgyLTE=
# content-type: application/json

# {
#     "title": "test project",
#     "color":0
# }

# # DELETE PROJECT
# DELETE http://localhost:8080/project/36
# Authorization: NzlkYmViODE2NTgyLTE=

# # GET TASKS
# GET http://localhost:8080/taskProject/2
# Authorization: NzlkYmViODE2NTgyLTE=

# GET TASKS
# GET http://localhost:8080/task/
# Authorization: NzlkYmViODE2NTgyLTE=

# # GET TASK
# GET http://localhost:8080/task/5
# Authorization: NzlkYmViODE2NTgyLTE=

# # TASK CREATION
# POST  http://localhost:8080/task/
# Authorization: NzlkYmViODE2NTgyLTE=
# content-type: application/json

# {
#     "title": "first task",
#     "description": "description",
    # "StartDate": "2022-05-29 15:50:07.413562417 +0000 UTC",
    # "StopDate": "2022-05-29 15:50:07.413562417 +0000 UTC",
#     "projectId":2,
#     "statusId":0,
#     "cost":0
# }

# # TASK EDIT
# PUT  http://localhost:8080/task/
# Authorization: NzlkYmViODE2NTgyLTE=
# content-type: application/json

# {
#     "title": "api docs", 
#     "description": "", 
#     "projectId": 2, 
#     "StartDate": "2022-05-29 15:50:07.413562417 +0000 UTC",
#     "StopDate": "2022-05-29 15:50:07.413562417 +0000 UTC", 
#     "cost": 0, 
#     "statusId": 0,
#     "id": 111
# }

# # DELETE TASKS
# DELETE http://localhost:8080/task/111
# Authorization: NzlkYmViODE2NTgyLTE=


# # GET TASK MEMBERS
# GET http://localhost:8080/taskMembers/5
# Authorization: NzlkYmViODE2NTgyLTE=

# # ADD TASK MEMBER
# PUT http://localhost:8080/taskMembers/5?user_id=1
# Authorization: NzlkYmViODE2NTgyLTE=

# # DELETE TASK MEMBER
# DELETE http://localhost:8080/taskMembers/5?user_id=1
# Authorization: NzlkYmViODE2NTgyLTE=

# # GET INTERVALS
# GET http://localhost:8080/timeIntervals/5
# Authorization: NzlkYmViODE2NTgyLTE=

# # ADD INTERVAL
# POST http://localhost:8080/timeIntervals/5
# Authorization: NzlkYmViODE2NTgyLTE=

# # END INTERVAL
# PUT http://localhost:8080/timeIntervals/5
# Authorization: NzlkYmViODE2NTgyLTE=