services:
  go-app:
    build:
      context: ./
    container_name: go-app
    expose:
      - "80" # Expose http port
    restart: always
    volumes:
      - ./www:/usr/share/nginx/html/
    ports:
      - "80:8080"

  mariadb:
    build: './mariadb'
    container_name: mariadb
    restart: always
    expose:
      - "3306" # Expose http port
    env_file: ./mariadb/.env
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - mariadb-dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80


volumes:
  mariadb-dbdata:

