volumes:
  task_me_go_mariadb-dbdata:
     external: true

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
    volumes:
      - ./www:/usr/share/nginx/html/
    expose:
      - "80" # Expose http port
    ports:
      - "80:80"

  go-app:
    build:
      context: ./go_app
    container_name: go-app
    expose:
      - "80"
    restart: always
    ports:
      - "8080:8080"

  mariadb:
    build: './mariadb'
    container_name: mariadb
    restart: always
    expose:
      - "3306"
    env_file: ./mariadb/.env
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - task_me_go_mariadb-dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80




